name: Build and Push to GAR

on:
  workflow_dispatch:

env:
  PROJECT_ID: project-7909eb0c-53df-4426-b83
  GAR_LOCATION: asia-south1
  REPOSITORY: first-gar
  IMAGE: dummyspringapp
  PROJECT_NUMBER: 342052950863

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      id-token: write   #  REQUIRED for workload identity

    steps:
      #  Checkout repo
      - name: Checkout Code
        uses: actions/checkout@v4

      #  Setup Java
      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      #  Build spring app
      - name: Build Spring Boot App
        run: mvn clean package -DskipTests

      #  Authenticate to GCP
      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: projects/${{ env.PROJECT_NUMBER }}/locations/global/workloadIdentityPools/github-pool/providers/github-provider
          service_account: github-gar-push@${{ env.PROJECT_ID }}.iam.gserviceaccount.com

      #  Setup gcloud CLI
      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v2

      #  Configure Docker authentication
      - name: Configure Docker for GAR
        run: |
          gcloud auth configure-docker $GAR_LOCATION-docker.pkg.dev

      #  Build Docker image
      - name: Build Docker Image
        run: |
          docker build \
          -t $GAR_LOCATION-docker.pkg.dev/$PROJECT_ID/$REPOSITORY/$IMAGE:${{ github.sha }} .

      #  Push Docker image
      - name: Push Docker Image
        run: |
          docker push $GAR_LOCATION-docker.pkg.dev/$PROJECT_ID/$REPOSITORY/$IMAGE:${{ github.sha }}

      # # OPTIONAL: Trigger Team B Cloud Build
      # - name: Trigger Team B Cloud Build
      #   run: |
      #     gcloud builds triggers run TRIGGER_ID \
      #       --project=TEAM_B_PROJECT \
      #       --substitutions=_IMAGE=$GAR_LOCATION-docker.pkg.dev/$PROJECT_ID/$REPOSITORY/$IMAGE:${{ github.sha }}
